Code/Booking/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Booking.Models
{
    public class Room
    {
        public int Id { get; set; }
        public ApplicationUser User { get; set; }
        public Accomodation Accomodation { get; set; }
        public int Capacity { get; set; }
        public float Price { get; set; }
        public String Descritpion { get; set; }
        public bool Wifi { get; set; }
        public bool TV { get; set; }
        public bool PetFriendly { get; set; }
        public bool Terrace { get; set; }
        public bool AC { get; set; }
        public bool Parking { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime LastUpdate { get; set; }
    }
}

Code/Booking/Controllers/AccomodationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Booking.Models;
using Booking.Controllers;
using CSRedis;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using Booking.Helpers;
using Booking.ControlerViewModels;

namespace Booking.Controllers
{
    public class AccomodationController : Controller
    {
        private ApplicationDbContext _context;
        public RedisController redisDB;

        public AccomodationController()
        {
            _context = new ApplicationDbContext();
            redisDB = new RedisController();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Accomodation
        public ActionResult Index()
        {
            return View();
        }
        
        [Authorize]
        [Route("add-new-accomodation", Name = "add_new_accomodation")]
        public ActionResult AddNewAccomodation()
        {
            Accomodation accomodation = new Accomodation();
            List<City> cities = _context.Cities.ToList();
            AccomodationCities accomodationCities = new AccomodationCities
            {
                Accomodation = accomodation,
                Cities = cities
            };
            return View(accomodationCities);
        }

        [HttpPost]
        public ActionResult AddAccomodation(Accomodation accomodation)
        {
            var currentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            var user = _context.Users.Where(x => x.Email == currentUserName).FirstOrDefault();
          
            accomodation.User = user;
            accomodation.AvailableRooms = 0;
            accomodation.CreationDate = DateTime.Now;
            accomodation.LastUpdate = DateTime.Now;
            accomodation.Rating = 0;
            var city = _context.Cities.Where(x => x.Id == accomodation.CityIdNumber).FirstOrDefault();
            accomodation.City = city;
            _context.Accomodations.Add(accomodation);
            if (accomodation.Stars > 3)
            {
                redisDB.AddAccomodationToList("accomodationByStars", accomodation);
            }
            redisDB.AddAccomodationToList("accomodationNewest", accomodation);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("show-all-accomoations/{type}", Name ="show_all_accomodations")]
        public ActionResult ShowAllAccomodations(string type)
        {
            //var accomodations = _context.Accomodations.ToList();
            List<Accomodation> accomodations=null;
            if (type=="newest")
            {
                accomodations = redisDB.GetNewest();
            }
            if (type == "stars")
            {
                accomodations = redisDB.GetAboveAvergeStars();
            }
            return View(accomodations);
        }

        [HttpGet]
        [Authorize]
        [Route("show-user-accomoations", Name = "show_user_accomodations")]
        public ActionResult ShowAllAccomodationsByUser()
        {
            var currentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            var user = _context.Users.Where(x => x.Email == currentUserName).FirstOrDefault();
           
            var accomodations = _context.Accomodations.Where(a => a.User.Id == user.Id).ToList();
            return View(accomodations);
        }

        [Authorize]
        public ActionResult DeleteAccomodation(int id)
        {
            var accomodation = _context.Accomodations.Where(a => a.Id == id).FirstOrDefault();

            _context.Accomodations.Remove(accomodation);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        public int GetLastAccomodation()
        {
            Accomodation accomodation = _context.Accomodations.OrderByDescending(a => a.Id).FirstOrDefault();
            return accomodation.Id;
        }
    }
}

Code/Booking/Controllers/RoomController.cs
using Booking.Models;
using Booking.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Booking.Controllers
{
    public class RoomController : Controller
    {
        private ApplicationDbContext _context;

        public RoomController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Room
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [Route("add-new-room/{accomodationId}", Name ="add_new_room")]
        public ActionResult AddNewRoom(int accomodationId)
        {
            var room = new Room();
            var accomodation = _context.Accomodations.Where(a => a.Id == accomodationId).FirstOrDefault();
            room.Accomodation = accomodation;
            return View(room);
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddRoom(Room room, int accomodationId)
        {
            var currentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            var user = _context.Users.Where(x => x.Email == currentUserName).FirstOrDefault();
            var accomodation = _context.Accomodations.Where(a => a.Id == accomodationId).FirstOrDefault();

            room.User = user;
            room.CreationDate = DateTime.Now;
            room.LastUpdate = DateTime.Now;
            room.Accomodation = accomodation;

            accomodation.AvailableRooms++;
            //accomodation.Rooms.Add(room);

            _context.Rooms.Add(room);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("show-rooms/{accomodationId}/{type}", Name = "show_rooms")]
        public ActionResult ShowAllRoomsForAccomodation(int accomodationId, bool type)
        {
            var accomodation = _context.Accomodations.Where(a => a.Id == accomodationId).FirstOrDefault();
            var rooms = new List<Room>();
            rooms = _context.Rooms.Where(r => r.Accomodation.Id == accomodation.Id).ToList();
            City city = _context.Cities.Where(c => c.Id == accomodation.CityIdNumber).FirstOrDefault();
            AccomodationDetails accomomodationDetails = new AccomodationDetails
            {
                Accomodation = accomodation,
                Rooms = rooms,
                City=city
            };
            return View("ShowAllRoomsForAccomodation", accomomodationDetails);
        }
    }
}

Code/Booking/Views/Room/AddNewRoom.cshtml
@{
    ViewBag.Title = "AddNewRoom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Booking.Models.Room

<h2 style="margin:50px; text-align:center;">Dodajte novu smestajnu jedinicu</h2>
@using (@Html.BeginForm("AddRoom", "Room", new { accomodationId = Model.Accomodation.Id }, FormMethod.Post, null))
{
    <div class="form-group">
        <label>Maksimalan broj osoba</label>
        @Html.TextBoxFor(m => m.Capacity, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Cena dnevnog izdavanja (din)</label>
        @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
    </div>

    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.TV) TV
        </label>
    </div>

    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.PetFriendly) Pet Friendly
        </label>
    </div>

    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.AC) Klima
        </label>
    </div>

    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.Terrace) Terasa
        </label>
    </div>

    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.Parking) Parking mesto
        </label>
    </div>

    <div class="form-group">
        <label>Dodatni opis smestajne jedinice</label>
        @Html.TextAreaFor(m => m.Descritpion, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Dodaj</button>
}

Code/Booking/Views/Room/ShowAllRoomsForAccomodation.cshtml
@{
    ViewBag.Title = "ShowRooms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Booking.ViewModels.AccomodationDetails


<h2 style="text-align: center; margin-bottom:30px;">@Model.Accomodation.Name</h2>
<div class="col-lg-3" style="border-right:1px black solid; height:440px; font-size:20px;">
    <h3 style="text-align:center;">Informacije:</h3> </br>
    <div style="margin-bottom:10px;">
        <i class="fa fa-address-card" aria-hidden="true"></i> <b>Adresa: </br> </b>@Model.Accomodation.Address
    </div>
    <div style="margin-bottom:10px;">
        <i class="fa fa-star" aria-hidden="true"></i><b>Zvezdice: </b>@Model.Accomodation.Stars
    </div>
    <div style="margin-bottom:10px;">
        <i class="fa fa-check" aria-hidden="true"></i> <b>Ocena: </b>@Model.Accomodation.Rating
    </div>
    <div style="margin-bottom:10px;">
        <i class="fa fa-list-alt"></i> <b>Dodatni opis: </br> </b><div style="font-size:15px;">@Model.Accomodation.Description</div>
    </div>
</div>
<input id="coordinates" type="hidden" data-latitude=@Model.City.Latitude data-longitude=@Model.City.Longitude value=@Model.City />
<div class="col-lg-9">
    <div class="col-lg-10">
        <h3 style="text-align:center;">Lokacija:</h3> </br>
        <div id="map" style="height:200px">

        </div>
    </div>
    <div class="col-lg-2">
        <h3 style="text-align:center;">Vreme:</h3> </br>
        <div id="accomodationWeather">
            <h3 style="text-align:center;">Lokacija:</h3> </br>

        </div>
    </div>

    <div class="cardsWrapper row">
        @{
            foreach (var room in Model.Rooms)
            {
                <div class="card col-lg-4">

                    <h4> 1/@room.Capacity soba - @room.Accomodation.Name, @room.Accomodation.City </h4>
                    <h5> @room.Accomodation.City, @room.Accomodation.Country</h5>
                    <hr />
                    <div>
                        <b>Adresa: </b>@room.Accomodation.Address
                    </div>
                    <div>
                        <b>Cena (din): </b>@room.Price
                    </div>
                    <div>
                        <b>Ocena: </b>@room.Accomodation.Rating
                    </div>
                    <div class="row">
                        <div class="col-lg-7"><b>Wifi</b></div>
                        @{
                            if (room.Wifi)
                            {
                                <div class="col-lg-4"> <i class="fa fa-check"></i></div>
                            }
                            else
                            {
                                <div class="col-lg-4"> <i class="fa fa-times"></i></div>
                            }
                        }
                    </div>
                    <div class="row">
                        <div class="col-lg-7"><b>Parking</b></div>
                        @{
                            if (room.Parking)
                            {
                                <div class="col-lg-4"> <i class="fa fa-check"></i></div>
                            }
                            else
                            {
                                <div class="col-lg-4"> <i class="fa fa-times"></i></div>
                            }
                        }
                    </div>
                    <div class="row">
                        <div class="col-lg-7"><b>TV</b></div>
                        @{
                            if (room.TV)
                            {
                                <div class="col-lg-4"> <i class="fa fa-check"></i></div>
                            }
                            else
                            {
                                <div class="col-lg-4"> <i class="fa fa-times"></i></div>
                            }
                        }
                    </div>
                    <div class="row">
                        <div class="col-lg-7"><b>Dozvoljene zivotinje</b></div>
                        @{
                            if (room.PetFriendly)
                            {
                                <div class="col-lg-4"> <i class="fa fa-check"></i></div>
                            }
                            else
                            {
                                <div class="col-lg-4"> <i class="fa fa-times"></i></div>
                            }
                        }
                    </div>
                    <div class="row">
                        <div class="col-lg-7"><b>Terasa</b></div>
                        @{
                            if (room.Terrace)
                            {
                                <div class="col-lg-4"> <i class="fa fa-check"></i></div>
                            }
                            else
                            {
                                <div class="col-lg-4"> <i class="fa fa-times"></i></div>
                            }
                        }
                    </div>
                    <div class="row">
                        <div class="col-lg-7"><b>Klima</b></div>
                        @{
                            if (room.AC)
                            {
                                <div class="col-lg-4"> <i class="fa fa-check"></i></div>
                            }
                            else
                            {
                                <div class="col-lg-4"> <i class="fa fa-times"></i></div>
                            }
                        }
                    </div>
                    <div>
                        <b>Dodatni opis: </b>@room.Descritpion
                    </div>
                    <a class="btn btn-block btn-info" style="margin-top:10px;" href='@Url.RouteUrl("add_new_reservation", new { roomId = room.Id })'>Rezervisi smestajnu jedinicu</a>

                    @*<a class="btn btn-block btn-success" style="margin-top:10px;" href='@Url.RouteUrl("add_new_room", new { accomodationId = accomodation.Id })'>Izmeni smestajnu jedinicu</a>*@
                    @*@Html.ActionLink("Obrisi ovaj smestajni objekat", "DeleteAccomodation", "Accomodation", new { id = accomodation.Id }, new { @class = "btn btn-block btn-danger" })*@
                </div>
            }
        }
    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/accomodation")
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBrSg49lehHSCaDtWljrIE7uiwBxZRUIBY&callback=initMap">
    </script>
}