Code/Booking/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Booking.Models;
using Booking.ViewModels;

namespace Booking.Controllers
{
    public class ImageController : Controller
    {
        private ApplicationDbContext sqlDB;

        public ImageController()
        {
            sqlDB = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            sqlDB.Dispose();
        }

        [Authorize]
        [Route("add-new-image/{accomodationId}", Name = "add_new_image")]
        public ActionResult AddNewImage(int accomodationId)
        {
            ImageObject image = new ImageObject();
            var accomodation = sqlDB.Accomodations.Where(a => a.Id == accomodationId).FirstOrDefault();
            image.Accomodation = accomodation;

            return View(image);
        }

        [Authorize]
        [Route("add-image", Name = "add_image")]
        public ActionResult AddImage(ImageObject imageObject, int accomodationId)
        {
            string fileName = Path.GetFileNameWithoutExtension(imageObject.ImageFile.FileName);
            string extension = Path.GetExtension(imageObject.ImageFile.FileName);
            fileName = fileName + "" + extension;
            imageObject.ImagePath = "~/Content/images/accomodation/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Content/images/accomodation/"), fileName);
            imageObject.ImageFile.SaveAs(fileName);

            ImageModels image = new ImageModels();
            image.ImagePath = imageObject.ImagePath;
            image.Title = imageObject.Title;

            var accomodation = sqlDB.Accomodations.Where(a => a.Id == accomodationId).FirstOrDefault();
            image.Accomodation = accomodation;
            
            sqlDB.Images.Add(image);
            sqlDB.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [Route("show-images/{accomodationId}", Name = "show_images")]
        public ActionResult ShowImages(int accomodationId)
        {
            List<ImageModels> images = sqlDB.Images.Where(a => a.Accomodation.Id == accomodationId).ToList();
           
            return View(images);
        }
    }
}

Code/Booking/Views/Image/AddNewImage.cshtml
@model Booking.ViewModels.ImageObject

@{
    ViewBag.Title = "AddNewImage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Odabir slike</h2>

@using (Html.BeginForm("AddImage", "Image", new { accomodationId = Model.Accomodation.Id }, FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="Imagefile" required />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Odaberi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Code/Booking/Views/Image/ShowImages.cshtml
@{
    ViewBag.Title = "ShowImages";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<Booking.Models.ImageModels>

<h2 style="text-align:center; margin-bottom:30px">Fotografije</h2>

<div class="row">
    @{
        foreach (var image in Model)
        {
            <div class="col-lg-3" style="margin:20px">
                <img width="300" height="300" src="@Url.Content(image.ImagePath)" />
                <div style="margin-top: 20px; text-align:center; font-weight:bold;"> @image.Title </div>
            </div>

        }
    }
</div>