Code/Booking/Models/Reservation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Booking.Models
{
    public class Reservation
    {
        public int Id { set; get; }
        public ApplicationUser User { get; set; }
     //   [ForeignKey("Room")]
        public Room Room { get; set; }
        public float Price { get; set; }
        public DateTime DateStart { get; set; }
        public DateTime DateEnd { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime LastUpdate { get; set; }
        public String Comment { get; set; }
    }
}

Code/Booking/Controllers/ReservationController.cs
using Booking.ControlerViewModels;
using Booking.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Booking.Controllers
{
    public class ReservationController : Controller
    {
        private ApplicationDbContext sqlDB;
        private RedisController redisDB;

        public ReservationController()
        {
            sqlDB = new ApplicationDbContext();
            redisDB = new RedisController();
        }

        protected override void Dispose(bool disposing)
        {
            sqlDB.Dispose();
        }

        // GET: Reservation
        public ActionResult Index()
        {
            return View();
        }

        [Route("add-new-reservation/{roomId}", Name = "add_new_reservation")]
        public ActionResult AddNewReservation(int roomId)
        {
            var reservation = new Reservation();

            var room = sqlDB.Rooms.Where(r => r.Id == roomId).FirstOrDefault();
            reservation.Room = room;
            //reservation.DateStart = DateTime.Now;
            //reservation.DateEnd = DateTime.Now;

            ReservationDates reservationDates = new ReservationDates
            {
                Reservation = reservation,
                Dates = redisDB.GetReservationsDatesForRoom(roomId)
            };
            
            return View(reservationDates);
        }  

        [HttpPost]
        public ActionResult AddReservation(Reservation reservation, int roomId)
        {
            var currentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            var user = sqlDB.Users.Where(x => x.Email == currentUserName).FirstOrDefault();

            var room = sqlDB.Rooms.Where(r => r.Id == roomId).FirstOrDefault();

            reservation.Room = room;
            reservation.User = user;
            
            reservation.CreationDate = DateTime.Now;
            reservation.LastUpdate = DateTime.Now;

            sqlDB.Reservations.Add(reservation);
            sqlDB.SaveChanges();

            redisDB.AddReservation(reservation);

            return RedirectToAction("Index", "Home");
        }
    }
}

Code/Booking/Views/Reservation/AddNewReservation.cshtml
@{

    ViewBag.Title = "AddNewRoom";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@model Booking.ControlerViewModels.ReservationDates


<div class="hidden" id="flashDiv">Neko je upravo rezervisao ovu smestajnu jedinicu!</div>
<h2 style="margin:50px; text-align:center;">Dodajte novu rezervaciju za odabranu smestajnu jedinicu</h2>
@using (@Html.BeginForm("AddReservation", "Reservation", new { roomId = Model.Reservation.Room.Id }, FormMethod.Post, null))
{
    <div class="row">
        <div class="form-group col-lg-5">
            <label>Pocetni datum</label>
            <div class="datePickerWraper">
                @Html.TextBoxFor(m => m.Reservation.DateStart, new { @class = "form-control datePickerReservation", @id = "dateStart" })
            </div> 
        </div>

        <div class="form-group col-lg-3">
            <label>Krajnji datum</label>
            @Html.TextBoxFor(m => m.Reservation.DateEnd, new { @class = "form-control datePickerReservation", @id = "dateEnd" })
        </div>
    </div>

    <div class="form-group" style="margin-top:30px">
        <label>Dodatne napomene vezane za rezervaciju</label>
        @Html.TextAreaFor(m => m.Reservation.Comment, new { @class = "form-control" })
    </div>

    <button type="submit" id="addReservation" class="btn btn-primary">Dodaj</button>
    <input type="hidden" id="dates" value=@Model.Dates />
}

@section scripts {
    <script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    <script src="~/signalR/hubs"></script>
    @Scripts.Render("~/bundles/reservation")
}